Repository uccross/skyhookdm-arrow, pull requests merged in 2021-07, with the labels that each got.

#197 SKYHOOK-195: Add support for scanning IPC objects
  cpp/cmake_modules/FindArrowCls.cmake
  cpp/src/arrow/adapters/arrow-rados-cls/cls_arrow.cc
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/test.sh
  cpp/src/arrow/dataset/file_rados_parquet.cc
  cpp/src/arrow/dataset/file_rados_parquet.h
  cpp/src/arrow/dataset/file_rados_parquet_test.cc
  cpp/src/arrow/dataset/scanner.h
  cpp/src/gandiva/jni/CMakeLists.txt
  cpp/src/generated/ScanRequest_generated.h
  cpp/src/jni/dataset/CMakeLists.txt
  cpp/src/jni/orc/CMakeLists.txt
  cpp/src/plasma/CMakeLists.txt
  format/ScanRequest.fbs
Labels: lang-c++

#201 Added hands-on instructions
  cpp/src/arrow/adapters/arrow-rados-cls/docs/benchmarking.md
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/bench.py
Labels: lang-c++

#206 SKYHOOK-204: Add Design Paradigm section to architecture.md.
  cpp/src/arrow/adapters/arrow-rados-cls/docs/architecture.md
  cpp/src/arrow/adapters/arrow-rados-cls/docs/images/design_paradigm.png
Labels: lang-c++

#221 Multiple improvements to docs.
  .github/workflows/docs.yml
  cpp/src/arrow/adapters/arrow-rados-cls/README.md
  cpp/src/arrow/adapters/arrow-rados-cls/docs/architecture.md
Labels: lang-c++

#232 Remove ceph related dependencies
  ci/docker/linux-apt-jni.dockerfile
  cpp/src/gandiva/jni/CMakeLists.txt
  cpp/src/jni/dataset/CMakeLists.txt
  cpp/src/jni/orc/CMakeLists.txt
  cpp/src/plasma/CMakeLists.txt
Labels: gandiva, lang-c++

#217 Refactor RadosParquet to Skyhook
  .github/workflows/cpp.yml
  .github/workflows/docs.yml
  cpp/src/arrow/adapters/arrow-rados-cls/README.md
  cpp/src/arrow/adapters/arrow-rados-cls/cls_arrow.cc
  cpp/src/arrow/adapters/arrow-rados-cls/cls_arrow_test.cc
  cpp/src/arrow/adapters/arrow-rados-cls/docs/architecture.md
  cpp/src/arrow/adapters/arrow-rados-cls/docs/benchmarking.md
  cpp/src/arrow/adapters/arrow-rados-cls/docs/deploy.md
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/bench.py
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/build.sh
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/test.sh
  cpp/src/arrow/dataset/CMakeLists.txt
  cpp/src/arrow/dataset/api.h
  cpp/src/arrow/dataset/discovery.cc
  cpp/src/arrow/dataset/file_skyhook.cc
  cpp/src/arrow/dataset/file_skyhook.h
  cpp/src/arrow/dataset/file_skyhook_test.cc
  cpp/src/arrow/dataset/scanner.h
  cpp/src/arrow/dataset/scanner_internal.h
  cpp/src/jni/dataset/jni_wrapper.cc
  docs/source/cpp/api/formats.rst
  python/pyarrow/_dataset.pyx
  python/pyarrow/_rados.pxd
  python/pyarrow/_rados.pyx
  python/pyarrow/dataset.py
  python/pyarrow/tests/conftest.py
  python/pyarrow/tests/test_rados_parquet.py
Labels: lang-c++, lang-java, lang-python

#248 Move out SplittedParquetWriter
  python/pyarrow/rados.py
  python/pyarrow/tests/test_rados_parquet.py
Labels: lang-python
