Repository uccross/skyhookdm-arrow, pull requests merged in 2021-06, with the labels that each got.

#159 Make the deploy_ceph.sh script dynamic
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/deploy_ceph.sh
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/deploy_skyhook.sh
Labels: lang-c++

#162 Set striping strategy on the files
  ci/scripts/integration_ceph.sh
  cpp/src/arrow/adapters/arrow-rados-cls/cls_arrow.cc
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/deploy_ceph.sh
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/deploy_data.sh
  cpp/src/arrow/dataset/file_rados_parquet.h
  python/pyarrow/rados.py
Labels: lang-c++, lang-python

#163 Added docstrings to file_rados_parquet.cc/h
  cpp/src/arrow/dataset/file_rados_parquet.cc
  cpp/src/arrow/dataset/file_rados_parquet.h
Labels: documentation, lang-c++

#169 Add docstrings to cls_arrow.cc and file_rados_parquet.h.
  cpp/src/arrow/adapters/arrow-rados-cls/cls_arrow.cc
  cpp/src/arrow/dataset/file_rados_parquet.h
Labels: lang-c++, lang-python

#172 Fix docstring param in file_rados_parquet.h
  cpp/src/arrow/dataset/file_rados_parquet.h
Labels: lang-c++

#174 Support Different compression strategy
  cpp/src/arrow/dataset/file_rados_parquet.cc
  cpp/src/arrow/dataset/file_rados_parquet.h
Labels: lang-c++

#177 Make the ceph deploy script repeatable and fault tolerant
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/deploy_ceph.sh
  cpp/src/arrow/adapters/arrow-rados-cls/scripts/deploy_skyhook.sh
Labels: lang-c++

#181 Fix linting issues.
  python/pyarrow/_rados.pyx
  python/pyarrow/rados.py
Labels: lang-python

#186 Add a thread-safe connection abstraction for RadosCluster
  cpp/src/arrow/adapters/arrow-rados-cls/cls_arrow_test.cc
  cpp/src/arrow/dataset/file_rados_parquet.cc
  cpp/src/arrow/dataset/file_rados_parquet.h
  cpp/src/gandiva/jni/CMakeLists.txt
  cpp/src/jni/dataset/CMakeLists.txt
  cpp/src/jni/orc/CMakeLists.txt
  cpp/src/plasma/CMakeLists.txt
  python/pyarrow/_rados.pxd
  python/pyarrow/_rados.pyx
  python/pyarrow/rados.py
Labels: gandiva, lang-c++, lang-python

#189 stop threaded decompression in parallel fragment scanning scenarios
  cpp/src/arrow/dataset/file_rados_parquet.cc
  cpp/src/arrow/dataset/file_rados_parquet.h
  cpp/src/arrow/dataset/file_rados_parquet_test.cc
Labels: lang-c++
